### ISSUE TITLE
`ContentRectChanged` never getting triggered so `AndroidApp::content_rect` is always zero.

### ISSUE THREAD

**Issue by ArthurKValladares** [rust-mobile/android-activity#65]
On a winit application. Not sure if I'm missing something to cause the event to get triggered.

**Comment by rib** [comment]
Hey @ArthurKValladares 

By default many config changes simply result in an Android application being restarted instead of notifying you of the change.

It might be that you need to update your manifest to declare that you'd like to get notified about things like orientation and screen size changes without being restarted. See here: https://developer.android.com/guide/topics/resources/runtime-changes
